# ?????
spring.datasource.url=jdbc:mysql://localhost:3306/health_db?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root12345

# JPA??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ?????
server.port=8080

# Spring Boot 3.x ???????? max-http-request-header-size?
server.max-http-request-header-size=1024000
server.tomcat.max-http-header-size=1024000

# ??AI??
baidu.ai.app.id=7656157
baidu.ai.api.key=jkKg0j2aSFMprZX4VvoL3zea
baidu.ai.secret.key=8nQ6RwEPZlW257G3d3v7fKF5rWMNNjUQ

# ??????
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# ???????????????????
spring.web.resources.static-locations=classpath:/static/,file:./uploads/
spring.web.resources.add-mappings=true

